# Generated by Django 4.0.1 on 2022-01-31 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Congregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('number', models.IntegerField(unique=True, verbose_name='Número')),
                ('midweek_meeting_time', models.TimeField(default=datetime.time(19, 30), verbose_name='Horário da reunião de meio de semana')),
                ('weekend_meeting_time', models.TimeField(default=datetime.time(18, 0), verbose_name='Horário da reunião de fim de semana')),
                ('midweek_meeting_day', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')], default=4, verbose_name='Dia da reunião de meio de semana')),
                ('weekend_meeting_day', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')], default=0, verbose_name='Dia da reunião de fim de semana')),
                ('random_key', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, null=True, verbose_name='Nome completo')),
                ('telephone', models.CharField(blank=True, default='(00)00000-0000', max_length=16, verbose_name='Telefone')),
                ('gender', models.IntegerField(choices=[(0, 'Masculino'), (1, 'Feminino')], default=0, max_length=1, verbose_name='Sexo')),
                ('privilege', models.IntegerField(choices=[(0, 'Ancião'), (1, 'Servo Ministerial'), (2, 'Sem privilégio especial')], default=2, max_length=2, verbose_name='Privilégio especial')),
                ('modality', models.IntegerField(choices=[(0, 'Pioneiro Especial'), (1, 'Pioneiro Regular'), (2, 'Pioneiro Auxiliar'), (3, 'Publicador')], default=3, max_length=2, verbose_name='Ministério')),
            ],
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Número')),
                ('theme', models.CharField(max_length=80, unique=True, verbose_name='Tema')),
            ],
        ),
    ]
