# Generated by Django 4.0.1 on 2022-02-01 13:03

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='congregation',
            options={'verbose_name': 'congregação', 'verbose_name_plural': 'congregações'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'pessoa', 'verbose_name_plural': 'pessoas'},
        ),
        migrations.AlterModelOptions(
            name='speech',
            options={'verbose_name': 'discurso', 'verbose_name_plural': 'discursos'},
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Masculino'), (1, 'Feminino')], default=0, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='modality',
            field=models.IntegerField(choices=[(0, 'Pioneiro Especial'), (1, 'Pioneiro Regular'), (2, 'Pioneiro Auxiliar'), (3, 'Publicador')], default=3, verbose_name='Ministério'),
        ),
        migrations.AlterField(
            model_name='person',
            name='privilege',
            field=models.IntegerField(choices=[(0, 'Ancião'), (1, 'Servo Ministerial'), (2, 'Sem privilégio especial')], default=2, verbose_name='Privilégio especial'),
        ),
        migrations.CreateModel(
            name='UserJWCM',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telephone', models.CharField(blank=True, max_length=16, verbose_name='Telefone')),
                ('congregation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.congregation')),
            ],
            options={
                'verbose_name': 'usuário JWCM',
                'verbose_name_plural': 'usuários JWCM',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
