# Generated by Django 4.0.1 on 2022-02-01 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_congregation_options_alter_person_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=16, null=True, verbose_name='Telefone')),
                ('congregation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.congregation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfis',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='congregation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.congregation'),
        ),
        migrations.DeleteModel(
            name='UserJWCM',
        ),
    ]
