# Generated by Django 4.0.1 on 2022-03-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_person_congregation_delete_userjwcm'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='indicator_mic',
            field=models.BooleanField(default=False, verbose_name='Indicador/Microfone'),
        ),
        migrations.AddField(
            model_name='person',
            name='reader',
            field=models.BooleanField(default=False, verbose_name='Leitor'),
        ),
        migrations.AddField(
            model_name='person',
            name='student_parts',
            field=models.BooleanField(default=True, verbose_name='Partes de Estudante'),
        ),
        migrations.AlterField(
            model_name='person',
            name='telephone',
            field=models.CharField(blank=True, max_length=16, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=models.CharField(max_length=16, null=True, verbose_name='Telefone'),
        ),
    ]
