# Generated by Django 4.0.1 on 2022-03-05 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_person_indicator_mic_person_reader_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Data')),
                ('congregation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.congregation')),
                ('speaker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.person', verbose_name='Orador')),
                ('speech', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.speech', verbose_name='Discurso')),
            ],
        ),
    ]
