# Generated by Django 4.0.1 on 2022-03-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_speech_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='congregation',
            name='host',
            field=models.BooleanField(default=False, verbose_name='Congregação Anfitriã'),
        ),
    ]
