# Generated by Django 4.0.1 on 2022-03-22 01:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_congregation_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congregation',
            name='midweek_meeting_day',
            field=models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')], default=4, null=True, verbose_name='Dia da reunião de meio de semana'),
        ),
        migrations.AlterField(
            model_name='congregation',
            name='midweek_meeting_time',
            field=models.TimeField(default=datetime.time(19, 30), null=True, verbose_name='Horário da reunião de meio de semana'),
        ),
        migrations.AlterField(
            model_name='congregation',
            name='number',
            field=models.IntegerField(null=True, unique=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='congregation',
            name='random_key',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='congregation',
            name='weekend_meeting_day',
            field=models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')], default=0, null=True, verbose_name='Dia da reunião de fim de semana'),
        ),
        migrations.AlterField(
            model_name='congregation',
            name='weekend_meeting_time',
            field=models.TimeField(default=datetime.time(18, 0), null=True, verbose_name='Horário da reunião de fim de semana'),
        ),
    ]
