# Generated by Django 4.0.1 on 2022-04-09 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_congregation_midweek_meeting_day_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicAssignment',
        ),
        migrations.DeleteModel(
            name='Speech',
        ),
    ]
