# Generated by Django 4.0.1 on 2022-06-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='indicator_mic',
        ),
        migrations.RemoveField(
            model_name='person',
            name='reader',
        ),
        migrations.AddField(
            model_name='person',
            name='bible_study_reader',
            field=models.BooleanField(default=False, verbose_name='Leitor de Estudo Bíblico'),
        ),
        migrations.AddField(
            model_name='person',
            name='indicator',
            field=models.BooleanField(default=False, verbose_name='Indicador'),
        ),
        migrations.AddField(
            model_name='person',
            name='mic',
            field=models.BooleanField(default=False, verbose_name='Microfone'),
        ),
        migrations.AddField(
            model_name='person',
            name='note_sound_table',
            field=models.BooleanField(default=False, verbose_name='Notebook/Mesa de Som'),
        ),
        migrations.AddField(
            model_name='person',
            name='watchtower_reader',
            field=models.BooleanField(default=False, verbose_name='Leitor de A Sentinela'),
        ),
        migrations.AddField(
            model_name='person',
            name='zoom_indicator',
            field=models.BooleanField(default=False, verbose_name='Indicador Zoom'),
        ),
    ]
