# Generated by Django 4.0.1 on 2022-06-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_person_indicator_mic_remove_person_reader_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congregation',
            name='midweek_meeting_day',
            field=models.IntegerField(choices=[(6, 'Domingo'), (0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado')], default=3, null=True, verbose_name='Dia da reunião de meio de semana'),
        ),
        migrations.AlterField(
            model_name='congregation',
            name='weekend_meeting_day',
            field=models.IntegerField(choices=[(6, 'Domingo'), (0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado')], default=6, null=True, verbose_name='Dia da reunião de fim de semana'),
        ),
    ]
