# Generated by Django 4.0.1 on 2022-06-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_congregation_midweek_meeting_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='midweek_meeting_president',
            field=models.BooleanField(default=False, verbose_name='Presidente - Reunião de meio de semana'),
        ),
        migrations.AddField(
            model_name='person',
            name='weekend_meeting_president',
            field=models.BooleanField(default=False, verbose_name='Presidente - Reunião de fim de semana'),
        ),
    ]
