# Generated by Django 4.0.1 on 2022-06-16 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public_speeches', '0005_remove_weekendmeeting_congregation_and_more'),
        ('core', '0013_person_midweek_meeting_president_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congregation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.congregation')),
                ('speaker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.person', verbose_name='Orador')),
                ('speech', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='public_speeches.speech', verbose_name='Discurso')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100, verbose_name='Tema')),
                ('helper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='helper', to='core.person', verbose_name='Ajudante')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner', to='core.person', verbose_name='Dono da parte')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Meio de semana'), (1, 'Fim de semana')], default=0, verbose_name='Tipo de Reunião')),
                ('date', models.DateField(verbose_name='Data')),
                ('congregation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.congregation')),
                ('indicator_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.person')),
                ('indicator_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.person')),
                ('mic_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.person')),
                ('mic_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.person')),
                ('note_sound_table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.person')),
                ('parts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.part', verbose_name='midweek_meeting')),
                ('president', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.person')),
                ('public_speech', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.publicassignment')),
                ('reader_watchtower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.person')),
                ('ruling_watchtower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.person')),
                ('zoom_indicator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.person')),
            ],
        ),
    ]
