# Generated by Django 4.0.1 on 2022-06-16 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_publicassignment_part_meeting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'verbose_name': 'reunião', 'verbose_name_plural': 'reuniões'},
        ),
        migrations.AlterField(
            model_name='meeting',
            name='congregation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.congregation', verbose_name='Congregação'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='indicator_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.person', verbose_name='Indicador 1'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='indicator_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.person', verbose_name='Indicador 2'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='mic_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.person', verbose_name='Microfone 1'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='mic_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.person', verbose_name='Microfone 2'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='note_sound_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.person', verbose_name='Notebook/mesa de som'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='president',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.person', verbose_name='Presidente'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='reader_watchtower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.person', verbose_name='Leitor de A Sentinela'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='ruling_watchtower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.person', verbose_name='Dirigente de A Sentinela'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='zoom_indicator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.person', verbose_name='Indicador Zoom'),
        ),
    ]
