# Generated by Django 4.0.1 on 2022-06-18 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_meeting_options_alter_meeting_congregation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicassignment',
            options={'verbose_name': 'designação pública', 'verbose_name_plural': 'designações públicas'},
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='parts',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='public_speech',
        ),
        migrations.RemoveField(
            model_name='publicassignment',
            name='congregation',
        ),
        migrations.AddField(
            model_name='meeting',
            name='public_assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.publicassignment', verbose_name='Discurso público TODO'),
        ),
    ]
