# Generated by Django 4.0.1 on 2022-06-19 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_publicassignment_options_remove_meeting_parts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='indicator',
        ),
        migrations.RemoveField(
            model_name='person',
            name='mic',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='note_sound_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audio_video_operator', to='core.person', verbose_name='Notebook/mesa de som'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='public_assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.publicassignment', verbose_name='Designação Pública'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='zoom_indicator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audio_video_indicator', to='core.person', verbose_name='Indicador Zoom'),
        ),
    ]
