# Generated by Django 4.0.1 on 2022-06-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_person_indicator_remove_person_mic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='indicator',
            field=models.BooleanField(default=False, verbose_name='Indicador'),
        ),
        migrations.AddField(
            model_name='person',
            name='mic',
            field=models.BooleanField(default=False, verbose_name='Microfone'),
        ),
    ]
