# Generated by Django 4.0.1 on 2022-06-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_person_indicator_person_mic'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.UniqueConstraint(fields=('date', 'congregation'), name='unique_meeting_per_congregation'),
        ),
    ]
