# Generated by Django 4.0.1 on 2022-06-26 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_congregation_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Part',
        ),
    ]
