# Generated by Django 4.0.1 on 2022-08-18 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_delete_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='public_assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.publicassignment', verbose_name='Designação Pública'),
        ),
    ]
