# Generated by Django 4.0.1 on 2022-09-08 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_meeting_public_assignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='reader_watchtower',
            new_name='watchtower_reader',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='ruling_watchtower',
            new_name='watchtower_ruling',
        ),
    ]
