# Generated by Django 4.0.1 on 2022-11-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_meeting_final_song_meeting_initial_song_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='lpw',
            field=models.BooleanField(default=False, verbose_name='Testemunho Público Local'),
        ),
    ]
