# Generated by Django 4.0.1 on 2022-11-24 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lpw', '0001_initial'),
        ('core', '0025_person_lpw'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='lpw_availability',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lpw.availabilitylpw'),
        ),
    ]
