# Generated by Django 4.0.1 on 2022-11-24 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lpw', '0001_initial'),
        ('core', '0026_person_lpw_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='lpw',
        ),
        migrations.AddField(
            model_name='congregation',
            name='lpw',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lpw.availabilitylpw'),
        ),
    ]
