# Generated by Django 4.0.1 on 2022-11-24 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_person_lpw_congregation_lpw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congregation',
            name='lpw',
        ),
        migrations.RemoveField(
            model_name='person',
            name='lpw_availability',
        ),
    ]
