# Generated by Django 4.0.1 on 2022-04-17 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_profile'),
        ('public_speeches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicassignment',
            name='date',
        ),
        migrations.CreateModel(
            name='WeekendMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Data')),
                ('congregation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.congregation')),
                ('indicator_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.person')),
                ('indicator_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.person')),
                ('mic_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.person')),
                ('mic_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.person')),
                ('president', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.person')),
                ('public_speech', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='public_speeches.publicassignment')),
                ('reader_watchtower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reader_watchtower', to='core.person')),
                ('ruling_watchtower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ruling_watchtower', to='core.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
