# Generated by Django 4.0.1 on 2022-06-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_speeches', '0003_weekendmeeting_note_sound_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekendmeeting',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
    ]
