# Generated by Django 4.0.1 on 2022-11-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityLPW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunday_morning', models.BooleanField(default=False, verbose_name='Domingo - manhã')),
                ('sunday_afternoon', models.BooleanField(default=False, verbose_name='Domingo - tarde')),
                ('sunday_night', models.BooleanField(default=False, verbose_name='Domingo - noite')),
                ('monday_morning', models.BooleanField(default=False, verbose_name='Segunda - manhã')),
                ('monday_afternoon', models.BooleanField(default=False, verbose_name='Segunda - tarde')),
                ('monday_night', models.BooleanField(default=False, verbose_name='Segunda - noite')),
                ('tuesday_morning', models.BooleanField(default=False, verbose_name='Terça - manhã')),
                ('tuesday_afternoon', models.BooleanField(default=False, verbose_name='Terça - tarde')),
                ('tuesday_night', models.BooleanField(default=False, verbose_name='Terça - noite')),
                ('wednesday_morning', models.BooleanField(default=False, verbose_name='Quarta - manhã')),
                ('wednesday_afternoon', models.BooleanField(default=False, verbose_name='Quarta - tarde')),
                ('wednesday_night', models.BooleanField(default=False, verbose_name='Quarta - noite')),
                ('thursday_morning', models.BooleanField(default=False, verbose_name='Quinta - manhã')),
                ('thursday_afternoon', models.BooleanField(default=False, verbose_name='Quinta - tarde')),
                ('thursday_night', models.BooleanField(default=False, verbose_name='Quinta - noite')),
                ('friday_morning', models.BooleanField(default=False, verbose_name='Sexta - manhã')),
                ('friday_afternoon', models.BooleanField(default=False, verbose_name='Sexta - tarde')),
                ('friday_night', models.BooleanField(default=False, verbose_name='Sexta - noite')),
                ('saturday_morning', models.BooleanField(default=False, verbose_name='Sábado - manhã')),
                ('saturday_afternoon', models.BooleanField(default=False, verbose_name='Sábado - tarde')),
                ('saturday_night', models.BooleanField(default=False, verbose_name='Sábado - noite')),
            ],
        ),
    ]
