# Generated by Django 4.0.1 on 2022-11-24 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_congregation_lpw_and_more'),
        ('lpw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CongregationAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunday_morning', models.BooleanField(default=False, verbose_name='Domingo - manhã')),
                ('sunday_afternoon', models.BooleanField(default=False, verbose_name='Domingo - tarde')),
                ('sunday_night', models.BooleanField(default=False, verbose_name='Domingo - noite')),
                ('monday_morning', models.BooleanField(default=False, verbose_name='Segunda - manhã')),
                ('monday_afternoon', models.BooleanField(default=False, verbose_name='Segunda - tarde')),
                ('monday_night', models.BooleanField(default=False, verbose_name='Segunda - noite')),
                ('tuesday_morning', models.BooleanField(default=False, verbose_name='Terça - manhã')),
                ('tuesday_afternoon', models.BooleanField(default=False, verbose_name='Terça - tarde')),
                ('tuesday_night', models.BooleanField(default=False, verbose_name='Terça - noite')),
                ('wednesday_morning', models.BooleanField(default=False, verbose_name='Quarta - manhã')),
                ('wednesday_afternoon', models.BooleanField(default=False, verbose_name='Quarta - tarde')),
                ('wednesday_night', models.BooleanField(default=False, verbose_name='Quarta - noite')),
                ('thursday_morning', models.BooleanField(default=False, verbose_name='Quinta - manhã')),
                ('thursday_afternoon', models.BooleanField(default=False, verbose_name='Quinta - tarde')),
                ('thursday_night', models.BooleanField(default=False, verbose_name='Quinta - noite')),
                ('friday_morning', models.BooleanField(default=False, verbose_name='Sexta - manhã')),
                ('friday_afternoon', models.BooleanField(default=False, verbose_name='Sexta - tarde')),
                ('friday_night', models.BooleanField(default=False, verbose_name='Sexta - noite')),
                ('saturday_morning', models.BooleanField(default=False, verbose_name='Sábado - manhã')),
                ('saturday_afternoon', models.BooleanField(default=False, verbose_name='Sábado - tarde')),
                ('saturday_night', models.BooleanField(default=False, verbose_name='Sábado - noite')),
                ('lpw', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.congregation')),
            ],
            options={
                'verbose_name': 'Congregação - Disponibilidade TPL',
                'verbose_name_plural': 'Congregações - Disponibilidades TPL',
            },
        ),
        migrations.CreateModel(
            name='MonthLPW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PersonAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunday_morning', models.BooleanField(default=False, verbose_name='Domingo - manhã')),
                ('sunday_afternoon', models.BooleanField(default=False, verbose_name='Domingo - tarde')),
                ('sunday_night', models.BooleanField(default=False, verbose_name='Domingo - noite')),
                ('monday_morning', models.BooleanField(default=False, verbose_name='Segunda - manhã')),
                ('monday_afternoon', models.BooleanField(default=False, verbose_name='Segunda - tarde')),
                ('monday_night', models.BooleanField(default=False, verbose_name='Segunda - noite')),
                ('tuesday_morning', models.BooleanField(default=False, verbose_name='Terça - manhã')),
                ('tuesday_afternoon', models.BooleanField(default=False, verbose_name='Terça - tarde')),
                ('tuesday_night', models.BooleanField(default=False, verbose_name='Terça - noite')),
                ('wednesday_morning', models.BooleanField(default=False, verbose_name='Quarta - manhã')),
                ('wednesday_afternoon', models.BooleanField(default=False, verbose_name='Quarta - tarde')),
                ('wednesday_night', models.BooleanField(default=False, verbose_name='Quarta - noite')),
                ('thursday_morning', models.BooleanField(default=False, verbose_name='Quinta - manhã')),
                ('thursday_afternoon', models.BooleanField(default=False, verbose_name='Quinta - tarde')),
                ('thursday_night', models.BooleanField(default=False, verbose_name='Quinta - noite')),
                ('friday_morning', models.BooleanField(default=False, verbose_name='Sexta - manhã')),
                ('friday_afternoon', models.BooleanField(default=False, verbose_name='Sexta - tarde')),
                ('friday_night', models.BooleanField(default=False, verbose_name='Sexta - noite')),
                ('saturday_morning', models.BooleanField(default=False, verbose_name='Sábado - manhã')),
                ('saturday_afternoon', models.BooleanField(default=False, verbose_name='Sábado - tarde')),
                ('saturday_night', models.BooleanField(default=False, verbose_name='Sábado - noite')),
                ('lpw', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.person')),
            ],
            options={
                'verbose_name': 'Publicador - Disponibilidade TPL',
                'verbose_name_plural': 'Publicadores - Disponibilidades TPL',
            },
        ),
        migrations.DeleteModel(
            name='AvailabilityLPW',
        ),
    ]
