# Generated by Django 4.0.1 on 2022-11-30 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_congregation_midweek_meeting_day_and_more'),
        ('lpw', '0004_daylpw_delete_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daylpw',
            options={'verbose_name': 'Dia LPW', 'verbose_name_plural': 'Dias LPW'},
        ),
        migrations.RemoveField(
            model_name='congregationavailability',
            name='friday_afternoon',
        ),
        migrations.RemoveField(
            model_name='congregationavailability',
            name='friday_morning',
        ),
        migrations.RemoveField(
            model_name='congregationavailability',
            name='friday_night',
        ),
        migrations.RemoveField(
            model_name='congregationavailability',
            name='lpw',
        ),
        migrations.RemoveField(
            model_name='congregationavailability',
            name='monday_afternoon',
        ),
        migrations.RemoveField(
            model_name='congregationavailability',
            name='monday_morning',
        ),
        migrations.RemoveField(
            model_name='congregationavailability',
            name='monday_night',
        ),
        migrations.RemoveField(
            model_name='congregationavailability',
            name='saturday_afternoon',
        ),
        migrations.RemoveField(
            model_name='congregationavailability',
            name='saturday_morning',
        ),
        migrations.RemoveField(
            model_name='congregationavailability',
            name='saturday_night',
        ),
        migrations.RemoveField(
            model_name='congregationavailability',
            name='sunday_afternoon',
        ),
        migrations.RemoveField(
            model_name='congregationavailability',
            name='sunday_morning',
        ),
        migrations.RemoveField(
            model_name='congregationavailability',
            name='sunday_night',
        ),
        migrations.RemoveField(
            model_name='congregationavailability',
            name='thursday_afternoon',
        ),
        migrations.RemoveField(
            model_name='congregationavailability',
            name='thursday_morning',
        ),
        migrations.RemoveField(
            model_name='congregationavailability',
            name='thursday_night',
        ),
        migrations.RemoveField(
            model_name='congregationavailability',
            name='tuesday_afternoon',
        ),
        migrations.RemoveField(
            model_name='congregationavailability',
            name='tuesday_morning',
        ),
        migrations.RemoveField(
            model_name='congregationavailability',
            name='tuesday_night',
        ),
        migrations.RemoveField(
            model_name='congregationavailability',
            name='wednesday_afternoon',
        ),
        migrations.RemoveField(
            model_name='congregationavailability',
            name='wednesday_morning',
        ),
        migrations.RemoveField(
            model_name='congregationavailability',
            name='wednesday_night',
        ),
        migrations.RemoveField(
            model_name='daylpw',
            name='day_available',
        ),
        migrations.RemoveField(
            model_name='personavailability',
            name='friday_afternoon',
        ),
        migrations.RemoveField(
            model_name='personavailability',
            name='friday_morning',
        ),
        migrations.RemoveField(
            model_name='personavailability',
            name='friday_night',
        ),
        migrations.RemoveField(
            model_name='personavailability',
            name='lpw',
        ),
        migrations.RemoveField(
            model_name='personavailability',
            name='monday_afternoon',
        ),
        migrations.RemoveField(
            model_name='personavailability',
            name='monday_morning',
        ),
        migrations.RemoveField(
            model_name='personavailability',
            name='monday_night',
        ),
        migrations.RemoveField(
            model_name='personavailability',
            name='saturday_afternoon',
        ),
        migrations.RemoveField(
            model_name='personavailability',
            name='saturday_morning',
        ),
        migrations.RemoveField(
            model_name='personavailability',
            name='saturday_night',
        ),
        migrations.RemoveField(
            model_name='personavailability',
            name='sunday_afternoon',
        ),
        migrations.RemoveField(
            model_name='personavailability',
            name='sunday_morning',
        ),
        migrations.RemoveField(
            model_name='personavailability',
            name='sunday_night',
        ),
        migrations.RemoveField(
            model_name='personavailability',
            name='thursday_afternoon',
        ),
        migrations.RemoveField(
            model_name='personavailability',
            name='thursday_morning',
        ),
        migrations.RemoveField(
            model_name='personavailability',
            name='thursday_night',
        ),
        migrations.RemoveField(
            model_name='personavailability',
            name='tuesday_afternoon',
        ),
        migrations.RemoveField(
            model_name='personavailability',
            name='tuesday_morning',
        ),
        migrations.RemoveField(
            model_name='personavailability',
            name='tuesday_night',
        ),
        migrations.RemoveField(
            model_name='personavailability',
            name='wednesday_afternoon',
        ),
        migrations.RemoveField(
            model_name='personavailability',
            name='wednesday_morning',
        ),
        migrations.RemoveField(
            model_name='personavailability',
            name='wednesday_night',
        ),
        migrations.AddField(
            model_name='congregationavailability',
            name='afternoon',
            field=models.BooleanField(default=False, verbose_name='Tarde'),
        ),
        migrations.AddField(
            model_name='congregationavailability',
            name='congregation',
            field=models.ManyToManyField(to='core.Congregation', verbose_name='Disponibilidade'),
        ),
        migrations.AddField(
            model_name='congregationavailability',
            name='morning',
            field=models.BooleanField(default=False, verbose_name='Manhã'),
        ),
        migrations.AddField(
            model_name='congregationavailability',
            name='night',
            field=models.BooleanField(default=False, verbose_name='Noite'),
        ),
        migrations.AddField(
            model_name='congregationavailability',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], default=6, verbose_name='Dia da semana'),
        ),
        migrations.AddField(
            model_name='daylpw',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], default=6, verbose_name='Dia da semana'),
        ),
        migrations.AddField(
            model_name='personavailability',
            name='afternoon',
            field=models.BooleanField(default=False, verbose_name='Tarde'),
        ),
        migrations.AddField(
            model_name='personavailability',
            name='morning',
            field=models.BooleanField(default=False, verbose_name='Manhã'),
        ),
        migrations.AddField(
            model_name='personavailability',
            name='night',
            field=models.BooleanField(default=False, verbose_name='Noite'),
        ),
        migrations.AddField(
            model_name='personavailability',
            name='person',
            field=models.ManyToManyField(to='core.Person', verbose_name='Disponibilidade'),
        ),
        migrations.AddField(
            model_name='personavailability',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], default=6, verbose_name='Dia da semana'),
        ),
        migrations.AlterField(
            model_name='daylpw',
            name='afternoon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.person', verbose_name='Tarde'),
        ),
        migrations.AlterField(
            model_name='daylpw',
            name='afternoon_available',
            field=models.BooleanField(default=False, verbose_name='Disponibilidade - tarde'),
        ),
        migrations.AlterField(
            model_name='daylpw',
            name='morning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.person', verbose_name='Manhã'),
        ),
        migrations.AlterField(
            model_name='daylpw',
            name='morning_available',
            field=models.BooleanField(default=False, verbose_name='Disponibilidade - manhã'),
        ),
        migrations.AlterField(
            model_name='daylpw',
            name='night',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.person', verbose_name='Noite'),
        ),
        migrations.AlterField(
            model_name='daylpw',
            name='night_available',
            field=models.BooleanField(default=False, verbose_name='Disponibilidade - noite'),
        ),
    ]
