from jwcm.public_speeches.models import Speech

#Localmente, fiz pelo manage shell
#Preciso ver qual a melhor maneira de fazer isso em produção TODO

objs = Speech.objects.bulk_create([
        Speech(number=1, theme='Você conhece bem a Deus?'),
        Speech(number=2, theme='Você vai sobreviver aos últimos dias?'),
        Speech(number=3, theme='Você está avançando com a organização unida de Jeová?'),
        Speech(number=4, theme='Que provas temos de que Deus existe?'),
        Speech(number=5, theme='Você pode ter uma família feliz'),
        Speech(number=6, theme='O dilúvio dos dias de Noé e você'),
        Speech(number=7, theme='Imite a misericórdia de Jeová'),
        Speech(number=8, theme='Viva para fazer a vontade de Deus'),
        Speech(number=9, theme='Escute e faça o que a Bíblia diz'),
        Speech(number=10, theme='Seja honesto em tudo'),
        Speech(number=11, theme='Imite a Jesus e não faça parte do mundo'),
        Speech(number=12, theme='Deus quer que você respeite quem tem autoridade'),
        Speech(number=13, theme='Qual o ponto de vista de Deus sobre o sexo e o casamento?'),
        Speech(number=14, theme='Um povo puro e limpo honra a Jeová'),
        Speech(number=15, theme='‘Faça o bem a todos’'),
        Speech(number=16, theme='Seja cada vez mais amigo de Jeová'),
        Speech(number=17, theme='Glorifique a Deus com tudo o que você tem'),
        Speech(number=18, theme='Faça de Jeová a sua fortaleza'),
        Speech(number=19, theme='Como você pode saber seu futuro?'),
        Speech(number=20, theme='Chegou o tempo de Deus governar o mundo?'),
        Speech(number=21, theme='Dê valor ao seu lugar no Reino de Deus'),
        Speech(number=22, theme='Você está usando bem o que Jeová lhe dá?'),
        Speech(number=23, theme='A vida tem objetivo'),
        Speech(number=24, theme='Você encontrou “uma pérola de grande valor”?'),
        Speech(number=25, theme='Lute contra o espírito do mundo'),
        Speech(number=26, theme='(Indisponível)'),
        Speech(number=27, theme='Como construir um casamento feliz'),
        Speech(number=28, theme='Mostre respeito e amor no seu casamento'),
        Speech(number=29, theme='As responsabilidades e recompensas de ter filhos'),
        Speech(number=30, theme='Como melhorar a comunicação na família'),
        Speech(number=31, theme='Você tem consciência da sua necessidade espiritual?'),
        Speech(number=32, theme='Como lidar com as ansiedades da vida'),
        Speech(number=33, theme='Quando vai existir verdadeira justiça?'),
        Speech(number=34, theme='(Indisponível)'),
        Speech(number=35, theme='É possível viver para sempre? O que você precisa fazer?'),
        Speech(number=36, theme='Será que a vida é só isso?'),
        Speech(number=37, theme='Obedecer a Deus é mesmo a melhor coisa a fazer?'),
        Speech(number=38, theme='Como você pode sobreviver ao fim do mundo?'),
        Speech(number=39, theme='Confie na vitória divina!'),
        Speech(number=40, theme='(Indisponível)'),
        Speech(number=41, theme='Fiquem parados e vejam como Jeová os salvará'),
        Speech(number=42, theme='O efeito do Reino de Deus sobre você'),
        Speech(number=43, theme='Tudo o que Deus nos pede é para o nosso bem'),
        Speech(number=44, theme='Como os ensinos de Jesus podem ajudar você?'),
        Speech(number=45, theme='Continue andando no caminho que leva à vida'),
        Speech(number=46, theme='Fortaleça sua confiança em Jeová'),
        Speech(number=47, theme='(Indisponível)'),
        Speech(number=48, theme='Seja leal a Deus mesmo quando for testado'),
        Speech(number=49, theme='Será que um dia a Terra vai ser limpa?'),
        Speech(number=50, theme='Como sempre tomar as melhores decisões'),
        Speech(number=51, theme='Será que a verdade da Bíblia está mudando a sua vida?'),
        Speech(number=52, theme='Quem é o seu Deus?'),
        Speech(number=53, theme='Você pensa como Deus?'),
        Speech(number=54, theme='Fortaleça sua fé em Deus e em suas promessas'),
        Speech(number=55, theme='Você está fazendo um bom nome perante Deus?'),
        Speech(number=56, theme='Existe um líder em quem você pode confiar?'),
        Speech(number=57, theme='Como suportar perseguição'),
        Speech(number=58, theme='Quem são os verdadeiros seguidores de Cristo?'),
        Speech(number=59, theme='Ceifará o que semear'),
        Speech(number=60, theme='Quão significativa é a sua vida?'),
        Speech(number=61, theme='Nas promessas de quem você confia?'),
        Speech(number=62, theme='A única cura para a humanidade doentia'),
        Speech(number=63, theme='Tem você espírito evangelizador?'),
        Speech(number=64, theme='Você ama os prazeres ou a Deus?'),
        Speech(number=65, theme='Como podemos ser pacíficos num mundo cheio de ódio'),
        Speech(number=66, theme='Você também vai participar na colheita?'),
        Speech(number=67, theme='Medite na Bíblia e nas criações de Jeová'),
        Speech(number=68, theme='Guarda ressentimento ou é perdoador?'),
        Speech(number=69, theme='Por que mostrar amor abnegado?'),
        Speech(number=70, theme='Faça de Jeová a sua confiança'),
        Speech(number=71, theme='‘Mantenha-se desperto’ — Por que e como?'),
        Speech(number=72, theme='O amor identifica os cristãos verdadeiros'),
        Speech(number=73, theme='Como adquirir um coração sábio'),
        Speech(number=74, theme='Os olhos de Jeová nos observam'),
        Speech(number=75, theme='Reconhece a soberania de Jeová em sua vida?'),
        Speech(number=76, theme='Princípios bíblicos — podem nos ajudar a lidar com os problemas atuais?'),
        Speech(number=77, theme='Siga o proceder da hospitalidade'),
        Speech(number=78, theme='Sirva a Jeová com coração alegre'),
        Speech(number=79, theme='Amizade com Deus ou com o mundo: qual escolherá?'),
        Speech(number=80, theme='Baseia a sua esperança na ciência ou na Bíblia?'),
        Speech(number=81, theme='Quem está habilitado para ser ministro de Deus?'),
        Speech(number=82, theme='Jeová e Cristo fazem parte de uma trindade?'),
        Speech(number=83, theme='Tempo de julgamento da religião'),
        Speech(number=84, theme='Escapará do destino deste mundo?'),
        Speech(number=85, theme='Boas notícias num mundo violento'),
        Speech(number=86, theme='Orações que são ouvidas por Deus'),
        Speech(number=87, theme='Qual é a sua relação com Deus?'),
        Speech(number=88, theme='Por que viver segundo as normas da Bíblia?'),
        Speech(number=89, theme='Venham os que têm sede da verdade!'),
        Speech(number=90, theme='Faça o máximo para alcançar a verdadeira vida!'),
        Speech(number=91, theme='A presença do Messias e seu domínio'),
        Speech(number=92, theme='O papel da religião nos assuntos do mundo'),
        Speech(number=93, theme='Catástrofes naturais — como as encara?'),
        Speech(number=94, theme='A religião verdadeira atende às necessidades da sociedade humana'),
        Speech(number=95, theme='O conceito da Bíblia sobre práticas espíritas'),
        Speech(number=96, theme='O que vai acontecer com as religiões?'),
        Speech(number=97, theme='Permaneçamos inculpes em meio a uma geração pervertida'),
        Speech(number=98, theme='“A cena deste mundo está mudando”'),
        Speech(number=99, theme='Por que você pode confiar na Bíblia'),
        Speech(number=100, theme='Amizade verdadeira com Deus e com o próximo'),
        Speech(number=101, theme='Jeová — o Grandioso Criador'),
        Speech(number=102, theme='Preste atenção à Palavra Profética'),
        Speech(number=103, theme='Pode-se encontrar alegria em servir a Deus'),
        Speech(number=104, theme='Pais — estão construindo com materiais à prova de fogo?'),
        Speech(number=105, theme='Somos consolados em todas as nossas tribulações'),
        Speech(number=106, theme='Arruinar a Terra provocará retribuição divina'),
        Speech(number=107, theme='Tenha uma boa consciência neste mundo pecaminoso'),
        Speech(number=108, theme='Vença o medo do futuro'),
        Speech(number=109, theme='O Reino de Deus está próximo'),
        Speech(number=110, theme='Deus vem primeiro na vida familiar bem-sucedida'),
        Speech(number=111, theme='O que é realizado pela cura das nações'),
        Speech(number=112, theme='Como expressar amor num mundo que viola a lei'),
        Speech(number=113, theme='Jovens — como vocês podem ter uma vida feliz?'),
        Speech(number=114, theme='Apreço pelas maravilhas da criação de Deus'),
        Speech(number=115, theme='Como proteger-nos contra os laços de Satanás'),
        Speech(number=116, theme='Escolha sabiamente com quem irá associar-se!'),
        Speech(number=117, theme='Como vencer o mal com o bem'),
        Speech(number=118, theme='Olhemos os jovens do ponto de vista de Jeová'),
        Speech(number=119, theme='Por que é benéfico que os cristãos vivam separados do mundo'),
        Speech(number=120, theme='Por que se submeter à regência de Deus agora'),
        Speech(number=121, theme='Uma fraternidade mundial que será salva da calamidade'),
        Speech(number=122, theme='Paz global — de onde virá?'),
        Speech(number=123, theme='Por que os cristãos têm de ser diferentes?'),
        Speech(number=124, theme='Razões para crer que a Bíblia é de autoria divina'),
        Speech(number=125, theme='Por que a humanidade precisa de resgate?'),
        Speech(number=126, theme='Quem se salvará?'),
        Speech(number=127, theme='O que acontece quando morremos?'),
        Speech(number=128, theme='É o inferno um lugar de tormento ardente?'),
        Speech(number=129, theme='É a Trindade um ensino bíblico?'),
        Speech(number=130, theme='A Terra permanecerá para sempre'),
        Speech(number=131, theme='Será que o Diabo realmente existe?'),
        Speech(number=132, theme='Ressureição — a vitória sobre a morte!'),
        Speech(number=133, theme='Tem importância o que cremos sobre a nossa origem?'),
        Speech(number=134, theme='Devem os cristãos guardar o sábado?'),
        Speech(number=135, theme='A santidade da vida e do sangue'),
        Speech(number=136, theme='Será que Deus aprova o uso de imagens na adoração?'),
        Speech(number=137, theme='Ocorreram realmente os milagres da Bíblia?'),
        Speech(number=138, theme='Viva com bom juízo num mundo depravado'),
        Speech(number=139, theme='Sabedoria divina num mundo científico'),
        Speech(number=140, theme='Quem é realmente Jesus Cristo?'),
        Speech(number=141, theme='Quando terão fim os gemidos da criação humana?'),
        Speech(number=142, theme='Por que refugiar-se em Jeová'),
        Speech(number=143, theme='Confie no Deus de todo consolo'),
        Speech(number=144, theme='Uma congregação leal sob a liderança de Cristo'),
        Speech(number=145, theme='Quem é semelhante a Jeová, nosso Deus?'),
        Speech(number=146, theme='Use a educação para louvar a Jeová'),
        Speech(number=147, theme='Confie no poder salvador de Jeová'),
        Speech(number=148, theme='Você tem o mesmo conceito de Deus sobre a vida?'),
        Speech(number=149, theme='O que significa “andar com Deus”?'),
        Speech(number=150, theme='Este mundo está condenado à destruição?'),
        Speech(number=151, theme='Jeová é “uma altura protetora” para seu povo'),
        Speech(number=152, theme='Armagedom — por que e quando?'),
        Speech(number=153, theme='Tenha bem em mente o “atemorizante dia”!'),
        Speech(number=154, theme='O governo humano é pesado na balança'),
        Speech(number=155, theme='Chegou a hora do julgamento de Babilônia?'),
        Speech(number=156, theme='O Dia do Juízo — tempo de temor ou de esperança?'),
        Speech(number=157, theme='Como os verdadeiros cristãos adornam o ensino divino'),
        Speech(number=158, theme='Seja corajoso e confie em Jeová'),
        Speech(number=159, theme='Como encontrar segurança num mundo perigoso'),
        Speech(number=160, theme='Mantenha a identidade cristã!'),
        Speech(number=161, theme='Por que Jesus sofreu e morreu?'),
        Speech(number=162, theme='Seja liberto deste mundo em escuridão'),
        Speech(number=163, theme='Por que temer o Deus verdadeiro?'),
        Speech(number=164, theme='Será que Deus ainda está no controle?'),
        Speech(number=165, theme='Os valores de quem você preza?'),
        Speech(number=166, theme='Como enfrentar o futuro com fé e coragem'),
        Speech(number=167, theme='Ajamos sabiamente num mundo insensato'),
        Speech(number=168, theme='Você pode sentir-se seguro neste mundo atribulado!'),
        Speech(number=169, theme='Por que ser orientado pela Bíblia?'),
        Speech(number=170, theme='Quem está qualificado para governar a humanidade?'),
        Speech(number=171, theme='Poderá viver em paz agora — e para sempre!'),
        Speech(number=172, theme='Que reputação você tem perante Deus?'),
        Speech(number=173, theme='Existe uma religião verdadeira do ponto de vista de Deus?'),
        Speech(number=174, theme='Quem se qualificará para entrar no novo mundo de Deus?'),
        Speech(number=175, theme='O que prova que a Bíblia é autêntica?'),
        Speech(number=176, theme='Quando haverá verdadeira paz e segurança?'),
        Speech(number=177, theme='Onde encontrar ajuda em tempos de aflição?'),
        Speech(number=178, theme='Ande no caminho da integridade'),
        Speech(number=179, theme='Rejeite as fantasias do mundo, empenhe-se pelas realidades do Reino'),
        Speech(number=180, theme='A ressureição — por que essa esperança deve ser real para você'),
        Speech(number=181, theme='Já é mais tarde do que você imagina?'),
        Speech(number=182, theme='O que o Reino de Deus está fazendo por nós agora?'),
        Speech(number=183, theme='Desvie seus olhos do que é fútil'),
        Speech(number=184, theme='A morte é o fim de tudo?'),
        Speech(number=185, theme='Será que a verdade influencia sua vida?'),
        Speech(number=186, theme='Sirva em união com o povo feliz de Deus'),
        Speech(number=187, theme='Por que um Deus amoroso permite a maldade?'),
        Speech(number=188, theme='Você confia em Jeová?'),
        Speech(number=189, theme='Ande com Deus e receba bênçãos para sempre'),
        Speech(number=190, theme='Como se cumprirá a promessa de perfeita felicidade familiar'),
        Speech(number=191, theme='Como o amor e a fé vencem o mundo'),
        Speech(number=192, theme='Você está no caminho para a vida eterna?'),
        Speech(number=193, theme='Os problemas de hoje logo serão coisa do passado'),
        Speech(number=194, theme='Como a sabedoria de Deus nos ajuda')
        ])
