# Generated by Django 4.0.1 on 2022-04-17 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100, verbose_name='Tema')),
                ('helper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='helper', to='core.person', verbose_name='Ajudante')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner', to='core.person', verbose_name='Dono da parte')),
            ],
        ),
        migrations.CreateModel(
            name='MidweekMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Data')),
                ('congregation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.congregation')),
                ('indicator_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.person')),
                ('indicator_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.person')),
                ('mic_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.person')),
                ('mic_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.person')),
                ('parts', models.ManyToManyField(to='life_and_ministry.Part', verbose_name='midweek_meeting')),
                ('president', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
