# Generated by Django 4.0.1 on 2022-06-11 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_person_indicator_mic_remove_person_reader_and_more'),
        ('life_and_ministry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='midweekmeeting',
            name='note_sound_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.person'),
        ),
        migrations.AddField(
            model_name='midweekmeeting',
            name='zoom_indicator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.person'),
        ),
    ]
