# Generated by Django 4.0.1 on 2022-06-16 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('life_and_ministry', '0003_alter_midweekmeeting_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='helper',
        ),
        migrations.RemoveField(
            model_name='part',
            name='owner',
        ),
        migrations.DeleteModel(
            name='MidweekMeeting',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
    ]
