# Generated by Django 4.0.1 on 2022-06-26 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0021_delete_part'),
        ('life_and_ministry', '0004_remove_part_helper_remove_part_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.IntegerField(choices=[(0, 'Tesouros da Palavra de Deus'), (1, 'Faça seu melhor no ministério'), (2, 'Nossa vida cristã')], default=0, verbose_name='Seção')),
                ('theme', models.CharField(max_length=100, verbose_name='Tema')),
                ('assistant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='helper', to='core.person', verbose_name='Ajudante')),
                ('meeting', models.ManyToManyField(to='core.Meeting', verbose_name='Reunião')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner', to='core.person', verbose_name='Dono da parte')),
            ],
        ),
    ]
