# Generated by Django 4.0.1 on 2022-07-10 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life_and_ministry', '0006_alter_part_options_remove_part_assistant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Data'),
        ),
    ]
