# Generated by Django 4.0.1 on 2022-08-18 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('life_and_ministry', '0007_part_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifeandministryassignment',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='life_and_ministry.part', verbose_name='Parte'),
        ),
        migrations.AlterField(
            model_name='part',
            name='theme',
            field=models.CharField(max_length=255, verbose_name='Tema'),
        ),
    ]
