# Generated by Django 4.0.1 on 2022-08-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life_and_ministry', '0008_alter_lifeandministryassignment_part_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='theme',
            field=models.TextField(verbose_name='Tema'),
        ),
    ]
